### ISSUE TITLE
Several users can't connect at the same time

### ISSUE THREAD

**Issue by jcsombria** [UNEDLabs/rip-labview-server#1]
Multiuser not handled

**Comment by Ravenink** [comment]
I think this should be fixed by 445fca64add1d12b768d24c68e0185b795bc0d0e
We need testing for confirmation, though.

**Comment by Ravenink** [comment]
I tested the SSE connection with three different simultaneous clients and it worked fine. We still need to test whether several users could send POST request "at the same time".

**Comment by Ravenink** [comment]
Tested and working!
