### ISSUE TITLE
Special characters in strings

### ISSUE THREAD

**Issue by Dictino** [UNEDLabs/rip-labview-server#15]
Strings in Global_Configurations.vi are copied to json without escaping special characters.

Example: http://localhost:8080/RIP?expId=TestOK  Produces a good json response, that's fine.

But if "Description" field is changed from the current value "TestOK" to:

"Description in 
two lines"

Then the resulting json is ill formed.

The same occurs with other fields like "Name", "Authors", "Keywords" and so on...

We actually have BasicMethods/Sub_methods/Escape_json.vi that implements the escaping logic used in get method, maybe @jcsombria knows where to place this block to solve the issue.

**Comment by Ravenink** [comment]
Fixed in 5c12998f64abc3abe8e25f22a517fa63dfa4fef7

Thanks for your indications, @Dictino!
