### ISSUE TITLE
Missing implementation of basic methods 

### ISSUE THREAD

**Issue by jcsombria** [UNEDLabs/rip-labview-server#4]
Methods:
- get(expid, vars) -> expid = "id", variables = ["x", "y", ...]
- set(expid, variables, values) -> expid = "id", variables = ["x", "y", ...], values = ["10", "a", ...]
- start(expid) -> expid = "id"
- stop(expid) -> expid = "id"

**Comment by Ravenink** [comment]
In the JiL.js client for RIP we still send the connect(), openVi() and runVi() methods separately, even if we run the start() method that sends the three previous consecutively. Should we reimplement the client or should we add these three methods to the RIP labview server? I personally vote for the latter, as I think having the three methods may help in certain debugging/developing situations.
Also, the TODO list in the main page of the project gets a bit confusing with this issue, as the connect() and open() methods are listed there. So it is the start() method, but not the run() method.

**Comment by Dictino** [comment]
I have a patch ready, but I don´t have permissions to Push to this repository... 
Please give me the correct permissions and I will upload the code ;)

**Comment by Ravenink** [comment]
I think you should have permissions now.

**Comment by Dictino** [comment]
Fixed!

This are the low level server methods:

    - controls_lilst, indicators_list = open(expid)
    - close(expid)
    - start(expid) 
    - stop(expid)
    - read_names, values = get(expid, variables)
    - set(expid, variables, values)  

Where "expid" is the experience name (id) as configured in the globalConfiguration.vi.
"variables" and "values" are arrays of text variables = ["x", "y", ...], values = ["10", "a", ...].
Output "read_names" return only the names of the variables that were succesfuly read (not all requested if there is some error)
And finally each method returns also an error indicator.

 LV types supported are int32, double, string and boolean. If more types are needed please open other issue.

**Comment by Ravenink** [comment]
Shouldn't it support any type of int and double type in LabView? From your comment I understand it supports all double types but only int32.

**Comment by Ravenink** [comment]
Ping to @Dictino

**Comment by Dictino** [comment]
Now only the default integer (int32) and the default double are supported.
But we can add support to all numeric types (except for complex numbers) if you find it usefull...

**Comment by Ravenink** [comment]
Yes, I think it would be really nice to have support for all int and double types in labview. See issue #6
