### ISSUE TITLE
Support for all int and double types

### ISSUE THREAD

**Issue by Ravenink** [UNEDLabs/rip-labview-server#6]
Right now, only int32 and default double are supported, but all LabView int and double types should be supported

**Comment by Dictino** [comment]
let´s add support for more more numeric types!

**Comment by Ravenink** [comment]
Any chance we could get this done in the next couple of weeks, @Dictino ?

**Comment by Dictino** [comment]
Yes, I will try to solve it this week ;)

**Comment by Dictino** [comment]
¡Fixed!

Added support for all numeric types (except complex numbers)

int, Unsigned int  (all precisions I32, U64...)  -->   int 
Single, Extended double Float and fixed point -->  float 

¡Have a nice weekend!

**Comment by Ravenink** [comment]
Awesome! :-)
