### ISSUE TITLE
Error message returned by SSE must be in JSON

### ISSUE THREAD

**Issue by Ravenink** [UNEDLabs/rip-labview-server#9]
The error message the SSE web service returns when the expId parameter is not given must be in JSON and should be understood by the client.

**Comment by Ravenink** [comment]
Can you take care of it @jcsombria ?

**Comment by jcsombria** [comment]
Ok, I'm working on it

**Comment by Ravenink** [comment]
Thank you, @jcsombria 
I made some additional minor changes in the SSE implementation and tested it after your changes and it seems to be working. Changes have been uploaded in commit 3a4054226a7f59df28c083d912950ea5764f6d50
